name: Master
on:
  push:
    branches:
      - 'master'
      - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Init NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - name: Install Packages
        run: npm install
        shell: bash
      - name: Build
        run: npm run build
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
